language: node_js
node_js:
  - "6"
  - "5"
  - "4"
# install yarn via npm
before_install:
  - npm install -g yarn
# use yarn to install dependencies
install:
  - yarn install
cache:
  directories:
  - $HOME/.yarn-cache
# use yarn to install gulp-cli
before_script:
  - yarn global add gulp-cli
script: gulp test
